backend:
  name: git-gateway
  branch: main
media_folder: "static/images"
public_folder: "/images"

collections:
  - name: "pages"
    label: "Pages"
    files:
      - file: "content/about.md"
        label: "About Page"
        name: "about"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Layout", name: "layout", widget: "hidden", default: "about"}
          - label: "Team Members"
            name: "team"
            widget: "list"
            fields:
              - {label: "Name", name: "name", widget: "string"}
              - {label: "Position", name: "position", widget: "string"}
              - {label: "Description", name: "description", widget: "text"}
          - label: "Core Values"
            name: "values"
            widget: "list"
            fields:
              - {label: "Title", name: "title", widget: "string"}
              - {label: "Description", name: "description", widget: "text"}
              - {label: "Icon", name: "icon", widget: "select", options: ["coffee", "users", "leaf", "wand-2"]}
          - {label: "Body", name: "body", widget: "markdown"}
      
      # Added Home Page
      - file: "content/index.md"
        label: "Home Page"
        name: "home"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Layout", name: "layout", widget: "hidden", default: "home"}
          - label: "Hero Section"
            name: "hero"
            widget: "object"
            fields:
              - {label: "Heading", name: "heading", widget: "string"}
              - {label: "Subheading", name: "subheading", widget: "string"}
              - {label: "Background Image", name: "background_image", widget: "image"}
          - label: "Featured Sections"
            name: "features"
            widget: "list"
            fields:
              - {label: "Title", name: "title", widget: "string"}
              - {label: "Description", name: "description", widget: "text"}
              - {label: "Image", name: "image", widget: "image"}
          - {label: "Body", name: "body", widget: "markdown"}

      # Added Contact Page
      - file: "content/contact.md"
        label: "Contact Page"
        name: "contact"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Layout", name: "layout", widget: "hidden", default: "contact"}
          - label: "Contact Information"
            name: "contact_info"
            widget: "object"
            fields:
              - {label: "Address", name: "address", widget: "string"}
              - {label: "Phone", name: "phone", widget: "string"}
              - {label: "Email", name: "email", widget: "string"}
          - label: "Business Hours"
            name: "hours"
            widget: "list"
            fields:
              - {label: "Days", name: "days", widget: "string"}
              - {label: "Hours", name: "time", widget: "string"}
          - {label: "Map Embed Code", name: "map", widget: "text"}
          - {label: "Body", name: "body", widget: "markdown"}

  # Rest of your existing collections remain the same
  - name: "settings"
    label: "Settings"
    files:
      - file: "data/menu_settings.yaml"
        label: "Menu Settings"
        name: "menu_settings"
        fields:
          - {label: "Footer Note", name: "footer_note", widget: "text", default: "Prices are subject to change. Please ask our staff about daily specials and seasonal offerings."}

  - name: "gallery"
    label: "Gallery"
    folder: "content/gallery"
    create: true
    slug: "{{slug}}"
    fields:
      - label: "Title"
        name: "title"
        widget: "string"
      - label: "Images"
        name: "images"
        widget: "list"
        fields:
          - label: "Image"
            name: "src"
            widget: "image"
          - label: "Alt Text"
            name: "alt"
            widget: "string"
          - label: "Caption"
            name: "caption"
            widget: "string"