backend:
  name: git-gateway
  branch: main
media_folder: "static/images"
public_folder: "/images"

collections:
  - label: "Pages"
    name: "pages"
    files:
      - label: "About Page"
        name: "about"
        file: "content/about.md"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Layout", name: "layout", widget: "hidden", default: "about"}
          - label: "Team Members"
            name: "team"
            widget: "list"
            fields:
              - {label: "Name", name: "name", widget: "string"}
              - {label: "Position", name: "position", widget: "string"}
              - {label: "Description", name: "description", widget: "text"}
          - label: "Core Values" 
            name: "values"
            widget: "list"
            fields:
              - {label: "Title", name: "title", widget: "string"}
              - {label: "Description", name: "description", widget: "text"}
              - {label: "Icon", name: "icon", widget: "select", options: ["coffee", "users", "leaf", "wand-2"]}
      - label: "Menu Page"
        name: "Menu"
        file: "data/menu.yml"
        fields:
          - label: "Categories"
            name: "categories"
            widget: "list"
            fields:
              - {label: "Category Name", name: "name", widget: "string"}
              - label: "Menu Items"
                name: "items"
                widget: "list"
                fields:
                  - {label: "Item Name", name: "name", widget: "string"}
                  - {label: "Description", name: "description", widget: "text"}
                  - {label: "Single Price", name: "price", widget: "number", required: false, value_type: "float", min: 0, step: 0.01}
                  - label: "Sizes"
                    name: "sizes"
                    widget: "list"
                    required: false
                    fields:
                      - {label: "Size Name", name: "name", widget: "string"}
                      - {label: "Price", name: "price", widget: "number", value_type: "float", min: 0, step: 0.01}