backend:
  name: git-gateway
  branch: main
media_folder: "static/images"
public_folder: "images"
collections:
  - label: "Pages"
    name: "pages"
    files:
      - label: "About Page"
        name: "about"
        file: "./content/about.md"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Intro, name: intro, widget: markdown}
          - {label: Main Content, name: body, widget: markdown} 
        